version: 0.0
os: linux
files:
  - source: /target/estoque-0.0.1-SNAPSHOT.jar
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh
      runas: root