# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: estoque
      MONGO_INITDB_ROOT_PASSWORD: estoque

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: estoque
      ME_CONFIG_MONGODB_ADMINPASSWORD: estoque
